### ISSUE TITLE
Show the max evolution number regarding candies

### ISSUE THREAD

**Issue by vlechemin** [vinnymac/PokeNurse#123] opened 2016-08-24 09:04 UTC
In the column `Evolves`, show both numbers `(3/15)`, so we know how many more pokemons we need (3/15) or how many we need to sell (20/15).

Thanks :)

**Comment by iPaulis** [comment] 2016-08-24 10:23
This is a duplicate of #101

**Closed as completed** 2016-08-24 12:03 UTC
