### ISSUE TITLE
Random ms interval between transfers.

### ISSUE THREAD

**Issue by furier** [vinnymac/PokeNurse#74] opened 2016-08-11 12:25 UTC
Hey would be great with random time interval in ms between transfers to simulate looking around in the pokemon inventory. Even better would be to specify a range of ms, like: `3000-6000` which should give good results and not whole seconds which could be suspicious. Say all transfers were exactly 1,2,3,4 or 5 seconds in duration in between that could indicate that it is not a human doing the transferring.

**Comment by vinnymac** [comment] 2016-08-11 12:26
This is a duplicate of #56. We already do random intervals also, so you could edit the code easily to do custom ones.

**Closed as completed by vinnymac** 2016-08-11 12:26 UTC
Labels: Resolution: Duplicate

**Comment by furier** [comment] 2016-08-11 12:30
Sorry misread the other issue, only read "evolve" :)
