### ISSUE TITLE
Add possibility to toggle between grouped mode and expanded mode

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#118] opened 2016-08-23 17:15 UTC
It would be very nice to have an option to toggle between grouped mode (what we already have) and an expanded mode with an ungrouped list of all our pokemons so we can sort them in general. Specially to be able to sort them by CP or favourited, like in the game, or also by IV% it would be very interesting.
The expanded mode could have the following columns: Pokedex #, Sprite, PowerUp, Name, Nickname, CP and IV. Maybe also Candy and Evolves columns even though numbers would be repeating and Count column would be a bit useless in this mode. Or these last 3 columns could be only visible in the grouped mode as we have now, so the grouped view would be the best one for managing evolves and the expanded view would be the best for sorting and managing pokemon in general to see in a glance our strongest pokemons for fighting.

**Comment by vinnymac** [comment] 2016-08-23 21:12
Duplicate of #75

**Closed as completed by vinnymac** 2016-08-23 21:12 UTC
