### ISSUE TITLE
Can't log in: Fetching RPC endpoint failed

### ISSUE THREAD

**Issue by Hallomajora** [vinnymac/PokeNurse#208] opened 2017-03-11 03:41 UTC
Since the forced update lately I can't even get in despite updating...

![unbenannt](https://cloud.githubusercontent.com/assets/26339046/23820250/f8fe2f12-0614-11e7-9409-937090e8182a.JPG)

**Comment by vinnymac** [comment] 2017-03-11 04:44
Duplicate of #187

**Closed as completed by vinnymac** 2017-03-11 04:44 UTC
