### ISSUE TITLE
Login not possible with Google Account

### ISSUE THREAD

**Issue by mhastrich** [vinnymac/PokeNurse#205] opened 2017-03-10 11:39 UTC
When trying to login with Google account (Not using token) the login fails with:

Error: operation timed out after x ms, 5 tries with error: Fetching RPC endpoint failed, received status code 100

**Comment by ghost** [comment] 2017-03-10 11:44
Same issue here.
With or without Hash Key, with or without 2 step verification.

**Comment by vankike7** [comment] 2017-03-10 19:27
I have the same issue, trying to access with Google account but get the error. Is there any fix for this?
Thanks!

![image](https://cloud.githubusercontent.com/assets/26333292/23809954/37f95488-0595-11e7-824b-72dec200e29d.png)
![image](https://cloud.githubusercontent.com/assets/26333292/23809911/05e90ea2-0595-11e7-87b1-43994e4c4eb6.png)

**Comment by hacknug** [comment] 2017-03-10 21:12
Use the develop branch. Some users reported issues with the release version but `develop` seems to work fine for everyone. Info on how to get it running is here: https://github.com/vinnymac/PokeNurse#contributing

**Comment by vankike7** [comment] 2017-03-10 22:40
Hi hacknug, thanks for the quick reply but not sure how to use the instructions you sent. Where do I input those commands? 

git clone https://github.com/vinnymac/PokeNurse
cd PokeNurse
git checkout develop
yarn
yarn run dev

**Comment by mhastrich** [comment] 2017-03-10 23:39
You have to type it in your commandline but this won't work for you because you need to install some things before: 

- git
- node.js
- yarn

But it won't help, master and development are on the same commit so you can't login with google Account in the development mode, too (just tried it).

**Comment by vankike7** [comment] 2017-03-11 01:39
Damn, so no fix yet? Hope we can log in soon... thanks for your replies!

**Comment by vinnymac** [comment] 2017-03-11 02:15
Duplicate of #187

**Closed as completed by vinnymac** 2017-03-11 02:15 UTC

**Comment by mhastrich** [comment] 2017-03-11 12:37
I don't think it's the same issue.
You cannot login with google Account anymore, Pokenurse is unusable at the moment!
The other Bug was regarding to transfer  of multiple pokemon but at the moment you can't even see your pokemon because you can't login.

This is since 4-5 days with a google Account.

**Comment by vinnymac** [comment] 2017-03-11 16:08
@mhastrich PokeNurse hasn't changed, Niantic's API has changed, all RPC 100 errors are a blanket issue. If you can download an older version of PokeNurse and log in successfully and report how to reproduce with steps I will gladly investigate the issue.
