### ISSUE TITLE
Selected counter does not refresh after transfer

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#125] opened 2016-08-24 16:20 UTC
I just selected 12 pokemon, transfered them (using transfer all) and the selected counter was still showing 12. When I selected another pokemon it updated to 13.

I just followed the same steps and reproduced the bug, same result. Clicking the refresh button didnt refresh the counter either.

**Comment by mackhankins** [comment] 2016-08-24 17:12
I'll try to reproduce your error.  What OS?

**Comment by iPaulis** [comment] 2016-08-24 17:14
Windows 10

**Comment by mackhankins** [comment] 2016-08-24 17:19
@vinnymac `index.js?7168:264 Uncaught TypeError: Cannot read property 'pokemon_id' of null`

**Comment by mackhankins** [comment] 2016-08-24 18:01
@iPaulis we had this working and I think we pushed up some old code.  We'll push out 1.3.1 soon.  Good catch.

**Comment by vinnymac** [comment] 2016-08-24 18:37
Just pushed a fix for this to develop. We can fix the evolves issue and then release.

**Closed as completed** 2016-08-24 18:55 UTC
Labels: Type: Bug

**Comment by mouson** [comment] 2016-08-24 23:09
@vinnymac 

I'm MAC User and used v1.3.2, but this bug is still exist. when i evolve my pokemen.

**Comment by mackhankins** [comment] 2016-08-24 23:34
@mouson I'm a mac user on 1.3.2 and I can't reproduce this error anymore.  How did you do it?

Edit: never mind I see it.

**Comment by mouson** [comment] 2016-08-24 23:51
@mackhankins 

This gif record evolve my pokemen step. http://d.pr/i/1iGBP

that is old javascript file cache ?

**Comment by vinnymac** [comment] 2016-08-25 00:06
Weird I guess the wrong binaries were selected, I will recompile and upload.

EDIT: I reuploaded them, you can try to redownload and see if that helps.
